<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
	<!-- Cho phép dự án Test và API nhìn thấy các class/method internal của Domain -->
    <InternalsVisibleTo Include="FastUrl.Domain.Tests" />
    <InternalsVisibleTo Include="FastUrl.API" />
   </ItemGroup>
</Project>
